### ISSUE TITLE
Litecoind Testnet Error: Out of memory. Terminating.

### ISSUE THREAD

**Issue by hoangphuchieu** [ltc-mweb/litecoin#28]
I build and run lastest ltc-mweb on docker containers. [Dockerfile](https://gist.github.com/hoangphuchieu/8ccbba61413bf99b5e8f3de841fc09c3)

When I start litecoind -testnet an error has occurred during blockchain synchronization:
`Error: Out of memory. Terminating.` [this is full debug.log](https://github.com/ltc-mweb/litecoin/files/6295657/debug.log)

I have checked and there is no limit of memory for run docker containers
I tried changing some settings in litecoin.conf but it still doesn't work, the process still stops at block height 755
```
dbcache=128
maxmempool=50
maxconnections=3
par=2
```

**Comment by DavidBurkett** [comment]
Should be working in the latest code. Feel free to reopen if it's still an issue.
